apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reservations-staging

resources:
  - ../base

namePrefix: staging-

patches:
  - target:
      kind: Deployment
      name: reservation-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Ingress
      name: reservation-ingress
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: staging.reservations.local
